### ISSUE TITLE
Trouble reproducing example

### ISSUE THREAD

**Issue by eduardokapp** [zaucy/vscode-bazel-cpp-example#1]
Hi. I cloned this repo in hopes of running the two commands you mentioned in the README.md.

I do get this error when running `bazel run //:copy_compile_commands`:

```
Starting local Bazel server and connecting to it...
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
INFO: Repository bazel_compdb instantiated at:
  /Users/eduardokapp/Desktop/Estudos/vscode-bazel-cpp-example/WORKSPACE:14:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git.bzl:189:33: in <toplevel>
ERROR: /private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl:210:9: An error occurred during the fetch of repository 'bazel_compdb':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 180, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git.bzl", line 43, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 98, column 12, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 116, column 10, in _update
		fetch(ctx, git_repo)
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 150, column 13, in fetch
		_git(
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 186, column 15, in _git
		_error(ctx.name, ["git"] + start + list(args), st.stderr)
	File "/private/var/tmp/_bazel_eduardokapp/10b1ccf4a88cab284280890aabc80f9a/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 210, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @bazel_compdb:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
WARNING: Target pattern parsing failed.
ERROR: Skipping '//:copy_compile_commands': no such package '@@bazel_compdb//': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @bazel_compdb:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: no such package '@@bazel_compdb//': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @bazel_compdb:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
INFO: Elapsed time: 6.322s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

Any idea why is this? Is there any dependency I should have?

**Comment by zaucy** [comment]
this repo was made with a very old version bazel and some of the dependencies commits looks to no longer exist (judging from the error). My example repo is probably not the best reference anymore considering how out dated it is 😅

**Comment by zaucy** [comment]
You know what, I updated the example to be more modern - just for you. Enjoy!
